map_frame: $(arg map_frame)
base_frame: $(arg base_frame)
odom_frame: $(arg odom_frame)
map_udpate_interval: 2.0
maxUrange: 16.0
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 0.2
angularUpdate: 0.1
temporalUpdate: 3.0
resampleThreshold: 0.5
particles: 100
xmin: -50.0
ymin: -50.0
xmax: 50.0
ymax: 50.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
