---
plugins:
  - Movement
  - Elevator

pad:
  type: ps4
  num_of_buttons: 14
  num_of_axes: 14
  joy_topic: $(arg joy_topic)

Movement:
  type: robotnik_pad_plugins/Movement
  max_linear_speed: 1.5
  max_angular_speed: 3
  cmd_topic_vel: pad_teleop_virtual/cmd_vel
  config:
    button_deadman: 5
    axis_linear_x: 1
    axis_linear_y: 0
    axis_angular_z: 2
    button_speed_up: 3
    button_speed_down: 1
    button_kinematic_mode: 7

Elevator:
  type: robotnik_pad_plugins/Elevator
  elevator_service_name: robotnik_base_control/set_elevator
  config:
    deadman: 5
    axis_elevator: 10
