<?xml version="1.0"?>
<robot name="sensor_pilz_psen_scan"
  xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="sensor_pilz_psen_scan" params="prefix parent prefix_topic:='front_laser' *origin max_angle:=2.3562 min_angle:=-2.3562 gpu:=^|true">
    <xacro:property name="mass" value="1.53" /> <!-- src datasheet p 96 -->
    <xacro:property name="radius" value="0.051" /> <!-- src datasheet p 96 -->
    <xacro:property name="height" value="0.152" /> <!-- src datasheet p 96 -->
    <xacro:property name="dist_scanning_plane_top" value="0.0477" /> <!-- src datasheet p 96 -->
    <xacro:property name="dist_scanning_axis_rear" value="0.0525" /> <!-- src datasheet p 96 -->
    
    <joint name="${prefix}_base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${prefix}_base_link"/>
    </joint>

    <link name="${prefix}_base_link"/>

    <joint name="${prefix}_body_joint" type="fixed">
      <parent link="${prefix}_base_link" />
      <child link="${prefix}_body_link" />
      <origin rpy="0 0 0" xyz="${radius} 0 0"/>
    </joint>
    <!-- Location of scanner body -->
    <link name="${prefix}_body_link">
      <visual>
        <origin rpy="0 0 ${pi}" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://robotnik_sensors/meshes/pilz_psen.stl"/>
          <!--cylinder radius="${radius}" length="${height}" /-->
        </geometry>
        <material name="pilz_yellow" >
          <color rgba="1.0 0.722 0.196 1.0" />
        </material>
      </visual>
      <collision>
        <origin rpy="0 0 ${pi}" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://robotnik_sensors/meshes/pilz_psen.stl"/>
          <!--cylinder radius="${radius}" length="${height}" /-->
        </geometry>
      </collision>
      <inertial>
        <mass value="${mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="${1 / 12 * mass * (3 * radius * radius + height * height)}" ixy="0.0" ixz="0.0"
          iyy="${1 / 12 * mass * (3 * radius * radius + height * height)}" iyz="0.0"
          izz="${.5 * mass * (radius * radius)}" />
      </inertial>
    </link>

    <joint name="${prefix}_scan_joint" type="fixed">
      <parent link="${prefix}_body_link" />
      <child link="${prefix}_link" />
      <origin rpy="${pi} 0 0" xyz="0 ${radius - dist_scanning_axis_rear} ${height / 2 + dist_scanning_plane_top}"/>
    </joint>

    <!-- This is the location of the laser scan -->
    <link name="${prefix}_link">
    </link>

    

    <!-- Sick sensor sensor for simulation -->
    <sensor_pilz_psen_scan_gazebo />

  </xacro:macro>

  <xacro:macro name="sensor_pilz_psen_scan_gazebo">
    <gazebo reference="${prefix}_link">

      <xacro:if value="${gpu}">
        <xacro:property name="ray_type" value="gpu_ray" />
        <xacro:property name="plugin_lib" value="libgazebo_ros_gpu_laser.so" />
      </xacro:if>
      <xacro:unless value="${gpu}">
        <xacro:property name="ray_type" value="ray" />
        <xacro:property name="plugin_lib" value="libgazebo_ros_laser.so" />
      </xacro:unless>

      <sensor type="${ray_type}" name="${prefix}_sensor">
        <pose>0 0 0 0 0 0</pose>
        <visualize>false</visualize>
        <update_rate>12.5</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>541</samples>
              <resolution>1</resolution>
              <min_angle>${min_angle}</min_angle>
              <max_angle>${max_angle}</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.10</min>
            <max>30.0</max>
            <resolution>0.03</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.03</stddev>
          </noise>
        </ray>
        <plugin name="${prefix}_controller" filename="${plugin_lib}">
          <topicName>${prefix_topic}/scan</topicName>
          <frameName>/${prefix}_link</frameName>					<!-- if not global (leading /) sets the current namespace as a prefix (/ns/name_laser_link) -->
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

</robot>
