footprint: [[0.375, -0.34], [0.375, 0.34], [-0.375,0.34], [-0.375, -0.34]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.3

obstacle_laser_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: front_laser rear_laser
  front_laser: 
    data_type: LaserScan
    topic: $(arg front_scan_topic)
    marking: true
    clearing: true
  rear_laser: 
    data_type: LaserScan
    topic: $(arg rear_scan_topic)
    marking: true
    clearing: true

obstacle_camera_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: front_rgbd_to_scan
  front_rgbd_to_scan:
    data_type: LaserScan
    topic: $(arg front_rgbd_to_scan_topic)
    marking: true
    clearing: true
