// Generated by gencpp from file ptu_control/pan_tiltRequest.msg
// DO NOT EDIT!


#ifndef PTU_CONTROL_MESSAGE_PAN_TILTREQUEST_H
#define PTU_CONTROL_MESSAGE_PAN_TILTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ptu_control
{
template <class ContainerAllocator>
struct pan_tiltRequest_
{
  typedef pan_tiltRequest_<ContainerAllocator> Type;

  pan_tiltRequest_()
    : position()
    , velocity()
    , effort()  {
    }
  pan_tiltRequest_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , velocity(_alloc)
    , effort(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _position_type;
  _position_type position;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _velocity_type;
  _velocity_type velocity;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _effort_type;
  _effort_type effort;





  typedef boost::shared_ptr< ::ptu_control::pan_tiltRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ptu_control::pan_tiltRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pan_tiltRequest_

typedef ::ptu_control::pan_tiltRequest_<std::allocator<void> > pan_tiltRequest;

typedef boost::shared_ptr< ::ptu_control::pan_tiltRequest > pan_tiltRequestPtr;
typedef boost::shared_ptr< ::ptu_control::pan_tiltRequest const> pan_tiltRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ptu_control::pan_tiltRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ptu_control::pan_tiltRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ptu_control::pan_tiltRequest_<ContainerAllocator1> & lhs, const ::ptu_control::pan_tiltRequest_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.effort == rhs.effort;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ptu_control::pan_tiltRequest_<ContainerAllocator1> & lhs, const ::ptu_control::pan_tiltRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ptu_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ptu_control::pan_tiltRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ptu_control::pan_tiltRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ptu_control::pan_tiltRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ptu_control::pan_tiltRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ptu_control::pan_tiltRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ptu_control::pan_tiltRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ptu_control::pan_tiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36babe5d6b67eaa3e1ff033f2c809848";
  }

  static const char* value(const ::ptu_control::pan_tiltRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36babe5d6b67eaa3ULL;
  static const uint64_t static_value2 = 0xe1ff033f2c809848ULL;
};

template<class ContainerAllocator>
struct DataType< ::ptu_control::pan_tiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ptu_control/pan_tiltRequest";
  }

  static const char* value(const ::ptu_control::pan_tiltRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ptu_control::pan_tiltRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
;
  }

  static const char* value(const ::ptu_control::pan_tiltRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ptu_control::pan_tiltRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.effort);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pan_tiltRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ptu_control::pan_tiltRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ptu_control::pan_tiltRequest_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocity[i]);
    }
    s << indent << "effort[]" << std::endl;
    for (size_t i = 0; i < v.effort.size(); ++i)
    {
      s << indent << "  effort[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.effort[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PTU_CONTROL_MESSAGE_PAN_TILTREQUEST_H
