// Generated by gencpp from file ptu_control/pan_tilt.msg
// DO NOT EDIT!


#ifndef PTU_CONTROL_MESSAGE_PAN_TILT_H
#define PTU_CONTROL_MESSAGE_PAN_TILT_H

#include <ros/service_traits.h>


#include <ptu_control/pan_tiltRequest.h>
#include <ptu_control/pan_tiltResponse.h>


namespace ptu_control
{

struct pan_tilt
{

typedef pan_tiltRequest Request;
typedef pan_tiltResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pan_tilt
} // namespace ptu_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ptu_control::pan_tilt > {
  static const char* value()
  {
    return "2e2b5f145e29f6b78ab4fe0698b7903a";
  }

  static const char* value(const ::ptu_control::pan_tilt&) { return value(); }
};

template<>
struct DataType< ::ptu_control::pan_tilt > {
  static const char* value()
  {
    return "ptu_control/pan_tilt";
  }

  static const char* value(const ::ptu_control::pan_tilt&) { return value(); }
};


// service_traits::MD5Sum< ::ptu_control::pan_tiltRequest> should match
// service_traits::MD5Sum< ::ptu_control::pan_tilt >
template<>
struct MD5Sum< ::ptu_control::pan_tiltRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ptu_control::pan_tilt >::value();
  }
  static const char* value(const ::ptu_control::pan_tiltRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ptu_control::pan_tiltRequest> should match
// service_traits::DataType< ::ptu_control::pan_tilt >
template<>
struct DataType< ::ptu_control::pan_tiltRequest>
{
  static const char* value()
  {
    return DataType< ::ptu_control::pan_tilt >::value();
  }
  static const char* value(const ::ptu_control::pan_tiltRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ptu_control::pan_tiltResponse> should match
// service_traits::MD5Sum< ::ptu_control::pan_tilt >
template<>
struct MD5Sum< ::ptu_control::pan_tiltResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ptu_control::pan_tilt >::value();
  }
  static const char* value(const ::ptu_control::pan_tiltResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ptu_control::pan_tiltResponse> should match
// service_traits::DataType< ::ptu_control::pan_tilt >
template<>
struct DataType< ::ptu_control::pan_tiltResponse>
{
  static const char* value()
  {
    return DataType< ::ptu_control::pan_tilt >::value();
  }
  static const char* value(const ::ptu_control::pan_tiltResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PTU_CONTROL_MESSAGE_PAN_TILT_H
